<?php
// Détection ou définition de la langue
$lang = isset($_GET['lang']) && $_GET['lang'] === 'en' ? 'en' : 'fr';

$translations = [
    'fr' => [
        'contact' => 'Contact',
        'auteur' => 'JADI DIGITAL - Ingénierie logicielle & Conseil Metier',
        'hero_title' => 'Nous conçevons vos outils numériques de demain.',
        'hero_desc' => 'Forte de son expertise dans l\'ingénierie logicielle et le conseil stratégique, notre agence met son savoir-faire au service de vos projets digitaux les plus ambitieux.',
        'portfolio' => 'Explorer notre Portfolio',
        'expertise_mini_title' => 'Notre Savoir-Faire',
        'expertise_title' => 'Expertise Technique & Métier',
        'expertise_descr1_title' => 'Expertise en développement Web Full Stack',
        'expertise_descr1_desc' => 'Maîtrise avancée des écosystèmes de développement web modernes (Front & Back End) pour des applications performantes',
        'expertise_descr2_title' => 'Architecture & Design Logiciel',
        'expertise_descr2_desc' => 'Conception de structures logicielles modulaires et pérennes, garantissant une maintenance simplifiée et une scalabilité technique optimale.',
        'expertise_descr3_title' => 'Stratégie & Pilotage Produit',
        'expertise_descr3_desc' => 'Accompagnement de bout en bout: de la découverte produit à la livraison agile, garantissant l\'alignement total entre vos enjeux métier et la solution technique.',
        // Section Equipe
        'team_mini_title' => 'Notre Equipe',
        'team_title' => 'Un Duo gagnant',
        'khalid_titre' => 'Fondateur & Direction Technique',
        'khalid_desc' => 'Ingénieur de formation et expert tech, Khalid orchestre la vision technologique de JADI DIGITAL. Spécialiste des systèmes critiques et de l\'architecture "AI-Native", il fusionne expertise logicielle et stratégie business pour concevoir des solutions innovantes.',
        'sara_titre' => 'Direction Produit France',
        'sara_desc' => 'Product Owner chevronnée avec dix ans d\'expérience, Sara pilote l\'excellence produit chez JADI DIGITAL. Experte en méthodes Agiles et en FinTech, elle transforme les enjeux métiers complexes en solutions digitales performantes, axées sur la croissance et l\'expérience utilisateur.',
        'cv_download' => 'Télécharger le CV',
        // Fin Section Equipe
        // Section OUTILS
        'tools_mini_title' => 'Outils',
        'tools_title' => 'Méthodes & Piles Technologiques',
        'card1_title' => 'Stacks Technologiques',
        'card1_mini_title' => 'Développement Web & IA (Full Stack)',
        'card1_desc' => 'Nous concevons des plateformes web scalables et des solutions "AI-First" performantes.',
        'card2_title' => 'Ingénierie Logicielle',
        'card2_mini_title' => 'Systèmes & Optimisation',
        'card2_desc' => 'Expertise en couches basses pour une optimisation maximale des ressources et la gestion de systèmes critiques.',
        'card3_title' => 'Pilotage Produit',
        'card3_mini_title' => 'Approche Méthodologique',
        'card3_desc' => 'Accompagnement de bout en bout, de la découverte produit à la livraison agile, garantissant l\'alignement total entre vos enjeux métier et la solution technique.',
        // Fin Section OUTILS
        'footer_title' => 'Expertise Tech & Conseil Stratégique.',
        'portfolio_title' => 'Notre Portfolio',
        'portfolio_sub_title' => 'Réalisations',
        'portfolio_sub_title2' => 'Projets JADI DIGITAL',
        'project1_desc' => 'Système de gestion de réclamations clients haute performance. Intègre une logique métier complexe.',
        'project1_subtitle0' => 'Intègre une logique métier complexe.',
        'project1_subtitle1' => 'Base de données relationnelle optimisée',
        'project1_subtitle2' => 'Automatisation d\'emails (SMTP)',
        'project_details' => 'Voir le projet',
        'project2_title' => 'Lancement Carte Virtuelle VISA',
        'project2_desc' => 'Pilotage de bout en bout du premier produit de paiement digital pour MT Cash, en partenariat avec VISA.',
        'project2_subtitle1' => 'Cadrage MVP & Parcours 3D Secure',
        'project2_subtitle2' => 'Rédaction User Stories & Design Figma',
        'project2_subtitle3' => 'Coordination Agile & Tests d\'intégration',
        // Page Contact
        'contact_retour' => 'Retour',
        'contact_mini_title' => 'Parlons de votre projet',
        'contact_title' => 'Contact',
        'contact_nom' => 'Nom Complet',
        'contact_objet' => 'Objet',
        'contact_sendButton' => 'Envoyer le message',
        // Page Project 1
        'project1_page_mini_title' => 'Étude de Cas',
        'project1-page-header1' => 'Le Besoin',
        'project1-page-desc1' => 'Conception d\'une plateforme centralisée pour la gestion des réclamations clients, remplaçant les flux d\'emails désorganisés par un système de tickets structuré et auditable.',
        'project1-page-header2' => 'Solutions Techniques',
        'project1_page-table_1' => 'Moteur de Priorisation :',
        'project1_page-table_2' => 'calculant l\'urgence selon le type de contrat (SLA).',
        'project1_page-table_3' => 'Sécurité :',
        'project1_page-table_4' => 'Protection contre les injections SQL et failles XSS (Clean Code).',
        'project1_page-table_5' => 'Notifications :',
        'project1_page-table_6' => 'Système SMTP automatisé pour un suivi en temps réel.',
        'project1_page_access_title' => 'Accéder à la démonstration',
        'project1_page_access_button' => 'Lancer l\'application Helpdesk',
        'project1_page_aside_text1' => 'Temps de réponse réduit de 40%',
        'project1_page_aside_text2' => 'Base de données normalisée (3NF)',
        'project1_page_aside_text3' => 'Authentification robuste (Bcrypt)',
        // Page Project 2
        'project2_page_desc1' => 'Cadrage et lancement de la carte virtuelle VISA pour MT Cash. L\'objectif était de permettre aux utilisateurs de réaliser des paiements e-commerce via un parcours fluide, sécurisé et conforme aux normes bancaires.',
        'project2_page_feature1_title' => 'Stratégie Produit :',
        'project2_page_feature1_desc' => 'Définition du MVP avec CVV2 dynamique et intégration du protocole 3D Secure.',
        'project2_page_feature2_title' => 'Conception Agile :',
        'project2_page_feature2_desc' => 'Rédaction des User Stories, gestion du backlog et coordination des designs avec VISA.',
        'project2_page_feature3_title' => 'Pilotage Technique :',
        'project2_page_feature3_desc' => 'Tests d\'intégration avec le processeur de paiement et gestion des sprints de développement.',
        'project2_page_aside_text1' => 'Conformité aux normes VISA',
        'project2_page_aside_text2' => 'Activation de carte en temps réel',
        'project2_page_aside_text3' => 'Time-to-market optimisé',

        // ... ajoutez toutes vos clés ici
    ],
    'en' => [
        'contact' => 'Contact',
        'auteur' => 'JADI DIGITAL - Software Engineering & Business Consulting',
        'hero_title' => 'We design the digital tools of tomorrow.',
        'hero_desc' => 'With its expertise in software engineering and strategic consulting, our agency provides its expertise to your most ambitious digital projects.',
        'portfolio' => 'Explore Our Portfolio',
        'expertise_mini_title' => 'Our Skills',
        'expertise_title' => 'Technical & Business Expertise',
        'expertise_descr1_title' => 'Full Stack Web Development Expertise',
        'expertise_descr1_desc' => 'Advanced mastery of modern web development ecosystems (Front & Back End) for performant and scalable applications',
        'expertise_descr2_title' => 'Software Architecture & Design',
        'expertise_descr2_desc' => 'Modular and persistent software structures, ensuring simplified maintenance and optimal technical scalability.',
        'expertise_descr3_title' => 'Product Strategy & Pilotage',
        'expertise_descr3_desc' => 'From product discovery to agile delivery, ensuring alignment between business objectives and technical solution.',
        // Section Equipe
        'team_mini_title' => 'Our Team',
        'team_title' => 'A Winning Duo',
        'khalid_titre' => 'Founder & Technical Director',
        'khalid_desc' => 'A trained engineer and tech expert, Khalid orchestrates the technological vision of JADI DIGITAL. Specializing in critical systems and AI-Native architecture, he bridges the gap between software expertise and business strategy to design innovative solutions.',
        'sara_titre' => 'France Product Owner',
        'sara_desc' => 'A seasoned Product Owner with ten years of experience, Sara drives product excellence at JADI DIGITAL. Expert in Agile methodologies and FinTech, she transforms complex business challenges into high-performance digital solutions, focused on growth and user experience.',
        'cv_download' => 'Download CV',
        // Fin Section Equipe
        // Section OUTILS
        'tools_mini_title' => 'Tools',
        'tools_title' => 'Methods & Technological Stacks',
        'card1_title' => 'Technological Stacks',
        'card1_mini_title' => 'Web Development & IA (Full Stack)',
        'card1_desc' => 'We design scalable and performant web platforms and "AI-First" solutions.',
        'card2_title' => 'Software Engineering',
        'card2_mini_title' => 'Systems & Optimization',
        'card2_desc' => 'Expertise in low-level layers for optimal resource optimization and management of critical systems.',
        'card3_title' => 'Product Ownership',
        'card3_mini_title' => 'Methodological Approach',
        'card3_desc' => 'From product discovery to agile delivery, ensuring alignment between business objectives and technical solution.',
        // Fin Section OUTILS
        'footer_title' => 'Tech Expertise & Strategic Consulting.',
        'portfolio_title' => 'Our Portfolio',
        'portfolio_sub_title' => 'Works',
        'portfolio_sub_title2' => 'Projects JADI DIGITAL',
        'project1_desc' => 'High-performance claim management system. Integrates a complex business logic.',
        'project1_subtitle0' => 'Integrates a complex business logic.',
        'project1_subtitle1' => 'Optimized relational database',
        'project1_subtitle2' => 'Email automation (SMTP)',
        'project_details' => 'Project\'s details',
        'project2_title' => 'VISA Virtual Card Launch',
        'project2_desc' => 'End-to-end management of the first digital payment product for MT Cash, in partnership with VISA.',
        'project2_subtitle1' => 'MVP Scoping & 3D Secure Workflows',
        'project2_subtitle2' => 'User Stories & Figma Design Oversight',
        'project2_subtitle3' => 'Agile Coordination & Integration Testing',
        // Page Contact
        'contact_retour' => 'Back',
        'contact_mini_title' => 'Let\'s talk about your project',
        'contact_title' => 'Contact',
        'contact_nom' => 'Full Name',
        'contact_objet' => 'Subject',
        'contact_sendButton' => 'Send Message',
        // Page Project 1
        'project1_page_mini_title' => 'Case Study',
        'project1-page-header1' => 'The Need',
        'project1-page-desc1' => 'Designing a centralized platform for claim management, replacing disorganized email flows with a structured and auditable ticketing system.',
        'project1-page-header2' => 'Technical Solutions',
        'project1_page-table_1' => 'Priority Engine:',
        'project1_page-table_2' => 'Integrates a complex business logic.',
        'project1_page-table_3' => 'Security:',
        'project1_page-table_4' => 'Optimized relational database',
        'project1_page-table_5' => 'Notifications:',
        'project1_page-table_6' => 'Email automation (SMTP)',
        'project1_page_access_title' => 'Access the demo',
        'project1_page_access_button' => 'Go to the demo',
        'project1_page_aside_text1' => '40% faster response time',
        'project1_page_aside_text2' => 'Normalized database (3NF)',
        'project1_page_aside_text3' => 'Strong authentication (Bcrypt)',
        // Page Project 2
        'project2_page_desc1' => 'Scoping and launch of the VISA virtual card for MT Cash. The goal was to enable users to make e-commerce payments through a smooth, secure, and banking-compliant journey.',
        'project2_page_feature1_title' => 'Product Strategy:',
        'project2_page_feature1_desc' => 'MVP definition including dynamic CVV2 and 3D Secure protocol integration.',
        'project2_page_feature2_title' => 'Agile Design:',
        'project2_page_feature2_desc' => 'User Stories drafting, backlog management, and design coordination with VISA.',
        'project2_page_feature3_title' => 'Technical Steering:',
        'project2_page_feature3_desc' => 'Integration testing with payment processors and development sprint management.',
        'project2_page_aside_text1' => 'VISA standards compliance',
        'project2_page_aside_text2' => 'Real-time card activation',
        'project2_page_aside_text3' => 'Optimized time-to-market',
        // ... ajoutez toutes vos clés ici
    ]
];

function __($key)
{
    global $lang, $translations;
    return $translations[$lang][$key] ?? $key;
}
